### ISSUE TITLE
Bug: BlackboardSync._sync_task mishandles ValueError exception

### ISSUE THREAD

**Issue by cainanmahar** [sanjacob/BlackboardSync#107]
The exception handling in `_sync_task` incorrectly assumes that any `ValueError` is the result of an expired session. https://github.com/jacobszpz/BlackboardSync/blob/8e7acee46199e01596576155ec9b55458516fce9/blackboard_sync/sync.py#L174-L178

`pydantic.ValidationError` inherits from `ValueError`, causing `_sync_task` to handle validation errors with the above block. The result is that the application will assume that the session has expired when it has not. The application will then restart synchronization, validation will fail again, rinse, repeat. This loop does not break, and the user is provided no indication this is happening outside logs.

For SHSU specifically, the application:
1. Never downloads anything, and repeatedly queries the enrolled courses.
    - Caused by #105
2. Completes a partial download, and repeatedly re-downloads (and re-writes the files for) content.
    - Caused by #106

**Comment by jacobszpz** [comment]
I have made a tentative fix in 74eb23e6e5906645dc1804fb8b200c3169f3c750

Let me know if you get the chance to try it (maybe you will have to intentionally revert one of the previous pydantic fixes to see any difference in error handling).

**Comment by cainanmahar** [comment]
I will test it later today when I return to my machine.

> By the way, it would be good to officially support SHSU, let me know if you are interested.


I intended to submit a form along with these issues, but had to stop.

**Comment by cainanmahar** [comment]
> Let me know if you get the chance to try it (maybe you will have to intentionally revert one of the previous pydantic fixes to see any difference in error handling).

The handler does correctly fail out when it encounters an "invalid" response from SHSU. Though, I believe it may make more sense to use a user-defined exception type so that future errors from other libs and the stl don't get misinterpreted. I'm willing to take a crack at that refactor and make a PR if you'd like.

**Comment by jacobszpz** [comment]
Do you mean to throw a custom exception when the session expires instead of a generic ValueError?

If so, yeah we can do that.
Probably best to keep them in a separate `blackboard/exceptions.py` file, and to create a base class for `BlackboardAPIError` as a subclass of Exception, which can be subclassed for things like session expiration and other API error codes.
You are free to come up with better names.

When it comes to handling the session expiration, I believe the server will respond with a 401 status code, where the custom exception should be thrown. Might as well create another custom exception for the Private Course scenario, and throw the default BlackboardAPIError otherwise

```
                elif 'status' in response: 
                     self.logger.error(f"Code {response['status']}: {response['message']}") 
                     if response['status'] == 401: 
                         raise ValueError('Not authorized')  #change
                     if response['status'] == 403: 
                         if 'code' in response and response['code'] == 'bb-rest-course-is-private': 
                             raise ValueError('Private course') #change
                    raise ValueError('Server responded with an error code') #change
```

Finally, you will need to change the code in sync.py, to instead catch the custom exception and also handle a generic ValueError which isn't raised from the api.py module

Ill add the SHSU entry to the universities file and after all that I will prepare a new release, which I would appreciate if you can test once done.

Thank you for contributing

**Comment by jacobszpz** [comment]
@cainanmahar Are you still planning on making a PR? Not a problem if you've changed your mind, just let me know

**Comment by cainanmahar** [comment]
Oh, yes, sorry. I am still planning on it. I just had some things that required my immediate attention. I also need to make a new issue, because I had to do some configuration faffing to get the embedded web browser to display on my machine. It's an issue with Qt, but it might not be fixed for some time.

**Comment by jacobszpz** [comment]
Did you get around to identifying the issue with Qt? Please let me know

**Comment by cainanmahar** [comment]
I have to disable sandboxing in order to see anything in the browser. I'm struggling to find what I saw recently again, but it is a bug with Qt.
